# Generated by Django 2.2.7 on 2020-02-06 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('attributes_id', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'peselgen_metrics',
            },
        ),
    ]
