# Generated by Django 3.0 on 2020-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20191220_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmetrics',
            name='attributes',
            field=models.CharField(max_length=30),
        ),
    ]
