# Generated by Django 2.2.6 on 2019-10-20 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=11)),
                ('sex', models.CharField(max_length=1)),
                ('birthday', models.DateField(default=datetime.datetime(2019, 10, 20, 21, 7, 57, 237299, tzinfo=utc))),
            ],
        ),
    ]
