# Generated by Django 2.2.6 on 2019-10-20 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person_service', '0002_auto_20191020_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 22, 34, 35, 338774, tzinfo=utc)),
        ),
    ]
