# Generated by Django 2.2.6 on 2019-10-21 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person_service', '0004_auto_20191021_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 10, 9, 6, 742870, tzinfo=utc)),
        ),
    ]
