# Generated by Django 3.0 on 2019-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firs_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='p', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='n', max_length=12),
            preserve_default=False,
        ),
    ]
