# Generated by Django 3.0 on 2019-12-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20191220_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
