# Generated by Django 2.2.7 on 2020-02-06 11:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', jsonfield.fields.JSONField()),
            ],
            options={
                'db_table': 'peselgen_attributes',
            },
        ),
    ]
